apiVersion: v1
kind: Secret
metadata:
  name: frontend
type: Opaque
stringData:
  NEXT_PUBLIC_AUTH_SERVICE_BASE_URL: http://$(AUTH_SERVICE_SERVICE_HOST)
  NEXT_PUBLIC_PRODUCT_SERVICE_BASE_URL: http://$(PRODUCT_SERVICE_SERVICE_HOST)
  NEXT_PUBLIC_SEARCH_SERVICE_BASE_URL: http://$(SEARCH_SERVICE_SERVICE_HOST)