podTemplate(yaml: '''
    apiVersion: v1
    kind: Pod
    spec:
      containers:
      - name: docker
        image: docker:latest

        command:
        - sleep
        args:
        - 99d
''') {
  node(POD_LABEL) {
    stage('Build') {
      git 'https://github.com/JuanDavidBallesteros/rental_app.git'
      container('ubuntu') {
        stage('Building') {
          sh 'ls'
        }
      }
    }

    /* stage('Get a Golang project') {
      git url: 'https://github.com/hashicorp/terraform-provider-google.git', branch: 'main'
      container('golang') {
        stage('Build a Go project') {
          sh '''
            mkdir -p /go/src/github.com/hashicorp
            ln -s `pwd` /go/src/github.com/hashicorp/terraform
            cd /go/src/github.com/hashicorp/terraform && make
          '''
        }
      }
    } */

  }
}


