podTemplate(yaml: '''
    apiVersion: v1
    kind: Pod
    spec:
      containers:
      - name: docker
        image: docker:latest

        command:
        - sleep
        args:
        - 99d
''') {
  node(POD_LABEL) {
    stage('Build') {
      container('docker') {
        stage('Building') {
          sh 'apk update'  
          sh 'apk add git'
          withCredentials([usernamePassword(credentialsId: '84bffb7c-a3bf-44f4-9471-977870eeed88', 
          passwordVariable: 'pass', usernameVariable: 'user')]){
            sh label: 'Login to Github', script: '''
git clone https://$user:$pass@github.com/JuanDavidBallesteros/rental_app.git . '''
          }
          sh 'docker build -t auth .'
        }
        
      }
    }

  }
}


